<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover"><title>Samply</title><meta name="description" content="Stream privately and losslessly to any device. Use time-coded comments, versions, and more to collaborate on your projects."><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900"><script>(function(c,l,a,r,i,t,y){
          c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
          t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
          y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
      })(window, document, "clarity", "script", "mbfr7k1zj8");</script><script>!function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window,document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '1484128091741507'); 
      fbq('track', 'PageView');</script><script async src="https://www.googletagmanager.com/gtag/js?id=AW-16720492465"></script><script>window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-16720492465');</script><noscript><img height="1" width="1" src="https://www.facebook.com/tr?id=1484128091741507&ev=PageView
      &noscript=1"/></noscript><link rel="icon" href="/favicon.ico"><link rel="icon" href="img/icons/favicon-32x32.png" type="image/png" sizes="32x32"><link rel="icon" href="img/icons/favicon-16x16.png" type="image/png" sizes="16x16"><meta property="og:title" content="Samply · Audio file sharing"><meta property="og:description" content="Stream privately and losslessly to any device. Use time-coded comments, versions, and more to collaborate on your projects."><meta property="og:site_name" content="Samply"><meta property="og:url" content="https://samply.app"><meta property="og:image" content="/og-image.png"><meta name="apple-itunes-app" content="app-id=6463439253"><meta name="theme-color" content="#000000"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><link rel="mask-icon" href="img/icons/safari-pinned-tab.svg" color="#FFFFFF"><link rel="apple-touch-icon" href="img/icons/apple-touch-icon-152x152.png" sizes="152x152"><link rel="apple-touch-startup-image" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)" href="/img/splash/apple-launch-1170x2532.png"><link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)" href="/img/splash/apple-launch-828x1792.png"><script src="/md5.js"></script><script data-app-key="5k9bktacgzot968" src="https://www.dropbox.com/static/api/2/dropins.js" id="dropboxjs"></script><meta name="color-scheme" content="dark light"><script type="module" crossorigin src="/assets/index.839916c7.js"></script><link rel="stylesheet" href="/assets/index.d7a7d5d6.css"><link rel="manifest" href="/manifest.webmanifest"></head><body><div id="app"></div><noscript><strong>We're sorry but Samply doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="hidden-reCAPTCHA"></div></body></html>